"""empty message

Revision ID: 33eb1a5eb1c1
Revises: 43bd7e5a5c9b
Create Date: 2023-11-23 18:53:25.877319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eb1a5eb1c1'
down_revision = '43bd7e5a5c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'PROGRESS', 'DONE', name='statusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_model')
    # ### end Alembic commands ###
