"""Init lab8

Revision ID: 3539751ff583
Revises: 
Create Date: 2023-11-12 12:36:49.221576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3539751ff583'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'PROGRESS', 'DONE', name='statusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=125), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    op.drop_table('todo_model')
    # ### end Alembic commands ###
